# This just compiles the meteor/logic-solver.cc into a javascript file i.e.
#    build/release/bin/minisat-meteor.js

all: check-instrumemtation $(MINISAT)-meteor.js

## Load common Configuration ###################################

include Makefile.common

ECHO=@echo
ifeq ($(VERB),)
VERB=@
else
VERB=
endif

################################################################
#inherit any targets not found in this file from "Makefile"

# % matches everything not explicitly specified
%: inherit # "inherit" is just an empty command to run so we can specify a dependency on "Makefile"
	@$(MAKE) --file=Makefile $@ 
inherit: ;# the "inherit" command is a no-op

################################################################

# EMSCRIPTEN LINK/COMPILE FLAGS
# # flags reference: http://kripken.github.io/emscripten-site/docs/tools_reference/emcc.html
# #  and also https://github.com/emscripten-core/emscripten/blob/3.1.74/src/settings.js
# # Add -g instead of --closure 1 to make the output pretty instead of mangled.
LOGIC_SOLVER_LDFLAGS?=\
		-s EXPORTED_FUNCTIONS='[\
			"_addClause", \
			"_createTheSolver", \
			"_ensureVar", \
			"_free", \
			"_getConflictClause", \
			"_getConflictClauseSize", \
			"_getNumVars", \
			"_getSolution", \
			"_malloc", \
			"_retireVar", \
			"_solve", \
			"_solveAssuming", \
			"_unyo", \
			"_yo", \
			"ccall", \
			"cwrap", \
			"UTF8ToString", \
			"stringToUTF8", \
			"UTF16ToString", \
			"stringToUTF16", \
			"UTF32ToString", \
			"stringToUTF32", \
			"AsciiToString", \
			"intArrayFromString", \
			"intArrayToString", \
			"writeArrayToMemory", \
			"stackSave", \
			"stackAlloc", \
			"stackRestore", \
			"getValue", \
			"setValue" \
			]'  \
		-s MIN_NODE_VERSION=140000 \
		-s EXPORT_ALL=1 \
		-s WASM_ASYNC_COMPILATION=0 \
		-s MODULARIZE=1 \
		-s ASSERTIONS=1 \
		-s ALLOW_MEMORY_GROWTH=1 \
		-s NO_FILESYSTEM=1  \
		-s ENVIRONMENT=node \
		-s SINGLE_FILE=1 \
		--extern-pre-js ./meteor/extern-preamble.js  \
		--pre-js ./meteor/preamble.js  \



	# OTHER OPTIONS:
		#	-O3  \
		# -s MALLOC=emmalloc \
		# -s STACK_SIZE=16777216 \
		# -s INITIAL_MEMORY=64MB \
		# -s INITIAL_HEAP=64MB \

		# -s STACK_SIZE=131072 \

		# --pre-js ./meteor/preamble.js  \
		# -s IMPORTED_MEMORY=1 \
		# -s WASM=0 \
		# -s ENVIRONMENT=node \
		# -s NO_DYNAMIC_EXECUTION=0 \
		# -s SINGLE_FILE=1 \
		# -s WASM_ASYNC_COMPILATION=0 \
		# -s ALLOW_MEMORY_GROWTH=1 \
		# -s WASM=0
		# -s ABORTING_MALLOC=1 \
		# -sINLINING_LIMIT \

# ----------------------------------------------------------------
# Run with environment variable ENABLE_INSTRUMENTATION=true to enable
#   the hacky malloc instrumentation (for development use only).
# This will add the "-g" compile flag.
# Otherwise, the "--closure 1" flag will be used.
# 

ENABLE_INSTRUMENTATION ?= false
INSTRUMENTATION_FLAGS ?= -O0 -g3 --post-js ./meteor/postamble.js
OPTIMIZATION_FLAGS ?= -Oz -sINLINING_LIMIT -flto --closure 1

# check env var to enable/disable the hacky malloc instrumentation
check-instrumemtation:
	$(eval LOGIC_SOLVER_LDFLAGS += $(if $(filter $(ENABLE_INSTRUMENTATION),true), $(INSTRUMENTATION_FLAGS) , $(OPTIMIZATION_FLAGS)))


# CXXFLAGS += -I. -D __STDC_LIMIT_MACROS -D __STDC_FORMAT_MACROS -Wall -Wno-parentheses -Wextra
# LDFLAGS  += -Wall

.PHONY: $(MINISAT)-meteor.js

SRCS = meteor/logic-solver.cc $(wildcard minisat/core/*.cc) $(wildcard minisat/simp/*.cc) $(wildcard minisat/utils/*.cc)

$(MINISAT)-meteor.js:	check-instrumemtation $(BUILD_DIR)/release/bin/$(MINISAT)-meteor.js


## Build-type Compile-flags:
$(BUILD_DIR)/release/%.o:			CXXFLAGS +=$(MINISAT_REL) 


## Build-type Link-flags:
$(BUILD_DIR)/release/bin/$(MINISAT)-meteor.js:		LDFLAGS += $(RELEASE_LDFLAGS) 
$(BUILD_DIR)/%/bin/$(MINISAT)-meteor.js:				LDFLAGS += $(LOGIC_SOLVER_LDFLAGS)

## Executable dependencies
$(BUILD_DIR)/release/bin/$(MINISAT)-meteor.js:	 	 $(BUILD_DIR)/release/lib/$(MINISAT_SLIB) $(BUILD_DIR)/release/meteor/logic-solver.o

## Compile rules (these should be unified, buit I have not yet found a way which works in GNU Make)
$(BUILD_DIR)/release/%.o:	%.cc
	$(VERB) $(ECHO) Compiling: $@
	$(VERB) mkdir -p $(dir $@)
	$(VERB) $(CXX) $(MINISAT_CXXFLAGS) $(CXXFLAGS) -c -o $@ $< -MMD -MF $(BUILD_DIR)/release/$*.d

## Linking rule - this will run emscripten
$(BUILD_DIR)/release/bin/$(MINISAT)-meteor.js:
	$(VERB) $(ECHO) ====== Linking Binary: $@
	$(VERB) $(ECHO) ====== Prerequisites: $^
	$(VERB) mkdir -p $(dir $@)
	$(VERB) $(CXX) $(EMSCRIPTEN_CXXFLAGS) $(CXXFLAGS) $^ $(LDFLAGS) $(EMSCRIPTEN_LDFLAGS) -o $@


clean:
	rm -rvf $(BUILD_DIR)


distclean:	clean
	rm -f config.mk


## Include generated dependencies
-include $(foreach s, $(SRCS:.cc=.d), $(BUILD_DIR)/release/$s)
