#!/bin/bash -e
set -eo pipefail

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

EMMAKE=emmake
EMCC=emcc
NODE=node

# -g turns off all the optimizations and compression
ENABLE_INSTRUMENTATION=${ENABLE_INSTRUMENTATION:-false}
if [ "${1}" == "-g" ]; then
  ENABLE_INSTRUMENTATION="true"
fi

echo "Building"

mkdir -p ${DIR}/../build
rm -rf ${DIR}/../build/*
# make minisat static library
$EMMAKE make -s -C "${DIR}/.." lr 

# make meteor minisat JS wrapper
$EMMAKE make -s \
    ENABLE_INSTRUMENTATION=${ENABLE_INSTRUMENTATION} \
    minisat-meteor.js \
    -C "${DIR}/.." \
    --file=Makefile.meteor

( echo "// This file is generated by the meteor/minisat repo." ; \
    echo "// See that repo's README for instructions for building it." \
) > ${DIR}/../build/minisat.js

if [ "${ENABLE_INSTRUMENTATION}" = "true" ]; then
    echo "Instrumentation enabled; set env var ENABLE_INSTRUMENTATION=false to disable instrumentation"
    ( sed -e "/^[[:space:]]*\/\/ EMSCRIPTEN_END_FUNCS/r ${DIR}/midamble.js" \
    ${DIR}/../build/release/bin/minisat-meteor.js ) >> ${DIR}/../build/minisat.js
else
    echo "Instrumentation NOT enabled; set env var ENABLE_INSTRUMENTATION=true to enable instrumentation and disable minification"
    ( cat ${DIR}/../build/release/bin/minisat-meteor.js ) >> ${DIR}/../build/minisat.js
fi

if [ -f "${DIR}/../build/release/bin/minisat-meteor.wasm" ]; then
    cp "${DIR}/../build/release/bin/minisat-meteor.wasm" ${DIR}/../build/
fi

echo "Testing"
$NODE ${DIR}/test/test.js
