#!/bin/bash -e
DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

EMMAKE=emmake
EMCC=emcc
NODE=node
MINISAT=${MINISAT:-"mergesat"}

echo "Building"

mkdir -p ${DIR}/build
rm -rf ${DIR}/build/*
$EMMAKE make lr -f ${DIR}/../Makefile # make minisat static library

# make meteor minisat JS wrapper
$EMMAKE make \
    ENABLE_INSTRUMENTATION=${ENABLE_INSTRUMENTATION:-false} \
    -f ${DIR}/../Makefile.meteor \
    ${MINISAT}-meteor.js

( echo "// This file is generated by the meteor/minisat repo." ; \
    echo "// See that repo's README for instructions for building it." \
) > ${DIR}/../build/${MINISAT}.js

if [ "${ENABLE_INSTRUMENTATION}" = "true" ]; then
    echo "Instrumentation enabled; set env var ENABLE_INSTRUMENTATION=false to disable instrumentation"
    ( sed -e "/^[[:space:]]*\/\/ EMSCRIPTEN_END_FUNCS/r ${DIR}/midamble.js" \
    build/release/bin/${MINISAT}-meteor.js ) >> ${DIR}/../build/${MINISAT}.js
else
    echo "Instrumentation NOT enabled; set env var ENABLE_INSTRUMENTATION=true to enable instrumentation and disable minification"
    ( cat build/release/bin/${MINISAT}-meteor.js ) >> ${DIR}/../build/${MINISAT}.js
fi


echo "Testing"
cd ${DIR}/test
npm install
$NODE ${DIR}/test/test.js
